# Generated by Django 6.0.2 on 2026-02-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='ord_items_order_del_idx',
            old_name='order_items_order_is_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='order_items_is_del_idx',
            old_name='order_items_is_deleted_idx',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
