# Generated by Django 6.0.2 on 2026-02-24

from decimal import Decimal
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(default='')),
                ('emoji', models.CharField(default='', max_length=10)),
                ('color', models.CharField(default='var(--primary-pink)', help_text='CSS color variable or hex color for category', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'indexes': [
                    models.Index(fields=['name'], name='categories_name_idx'),
                    models.Index(fields=['is_deleted'], name='categories_is_deleted_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ['name'],
                'indexes': [
                    models.Index(fields=['name'], name='brands_name_idx'),
                    models.Index(fields=['is_active'], name='brands_is_active_idx'),
                    models.Index(fields=['is_deleted'], name='brands_is_deleted_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price / discounted price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price (mandatory in India)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('mg', 'Milligram'), ('ltr', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('pack', 'Pack'), ('dozen', 'Dozen'), ('bunch', 'Bunch'), ('bottle', 'Bottle'), ('can', 'Can'), ('box', 'Box'), ('jar', 'Jar'), ('other', 'Other')], db_index=True, default='piece', max_length=20)),
                ('pack_size', models.DecimalField(blank=True, decimal_places=2, help_text='Pack size (e.g., 0.5 for 500g, 1 for 1kg, 6 for pack of 6)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('brand_name', models.CharField(blank=True, help_text='Denormalized copy for faster reads', max_length=100)),
                ('hsn_code', models.CharField(blank=True, max_length=8, null=True)),
                ('gst_rate', models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('0.25'), '0.25%'), (Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], db_index=True, default=Decimal('5.00'), max_digits=4, decimal_places=2)),
                ('is_veg', models.BooleanField(db_index=True, default=True)),
                ('is_organic', models.BooleanField(db_index=True, default=False)),
                ('is_fresh', models.BooleanField(db_index=True, default=False)),
                ('emoji', models.CharField(default='', max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.0'), max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['id'],
                'indexes': [
                    models.Index(fields=['name'], name='products_name_idx'),
                    models.Index(fields=['category', 'is_active'], name='products_category_is_active_idx'),
                    models.Index(fields=['brand'], name='products_brand_id_idx'),
                    models.Index(fields=['unit'], name='products_unit_idx'),
                    models.Index(fields=['mrp'], name='products_mrp_idx'),
                    models.Index(fields=['gst_rate'], name='products_gst_rate_idx'),
                    models.Index(fields=['is_veg'], name='products_is_veg_idx'),
                    models.Index(fields=['is_organic'], name='products_is_organic_idx'),
                    models.Index(fields=['is_fresh'], name='products_is_fresh_idx'),
                    models.Index(fields=['is_deleted'], name='products_is_deleted_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('discount_percent', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'db_table': 'combos',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['is_active'], name='combos_is_active_idx'),
                    models.Index(fields=['is_deleted'], name='combos_is_deleted_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ComboProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_products', to='products.combo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Combo Product',
                'verbose_name_plural': 'Combo Products',
                'db_table': 'combos_products',
                'indexes': [
                    models.Index(fields=['combo'], name='combos_products_combo_idx'),
                    models.Index(fields=['product'], name='combos_products_product_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='products',
            field=models.ManyToManyField(through='products.ComboProduct', related_name='combos', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='comboproduct',
            unique_together={('combo', 'product')},
        ),
    ]
