# Generated by Django 6.0.2 on 2026-02-24 09:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('discount_percent', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'combos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='brands_name_idx'), models.Index(fields=['is_active'], name='brands_is_active_idx'), models.Index(fields=['is_deleted'], name='brands_is_deleted_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='')),
                ('emoji', models.CharField(default='', max_length=10)),
                ('color', models.CharField(default='var(--primary-pink)', help_text='CSS color variable or hex color for category', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'indexes': [models.Index(fields=['name'], name='categories_name_idx'), models.Index(fields=['is_deleted'], name='categories_is_deleted_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price / discounted price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price (mandatory in India)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('mg', 'Milligram'), ('ltr', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('pack', 'Pack'), ('dozen', 'Dozen'), ('bunch', 'Bunch'), ('bottle', 'Bottle'), ('can', 'Can'), ('box', 'Box'), ('jar', 'Jar'), ('other', 'Other')], default='piece', max_length=20)),
                ('pack_size', models.DecimalField(blank=True, decimal_places=2, help_text='Pack size (e.g., 0.5 for 500g, 1 for 1kg, 6 for pack of 6)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('brand_name', models.CharField(blank=True, help_text='Denormalized copy for faster reads', max_length=100)),
                ('hsn_code', models.CharField(blank=True, max_length=8, null=True)),
                ('gst_rate', models.DecimalField(choices=[(0.0, '0%'), (0.25, '0.25%'), (5.0, '5%'), (12.0, '12%'), (18.0, '18%'), (28.0, '28%')], decimal_places=2, default=5.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(28.0)])),
                ('is_veg', models.BooleanField(default=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('is_fresh', models.BooleanField(default=False)),
                ('emoji', models.CharField(default='', max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ComboProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_products', to='products.combo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_products', to='products.product')),
            ],
            options={
                'db_table': 'combos_products',
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='products',
            field=models.ManyToManyField(related_name='combos', through='products.ComboProduct', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_category_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_brand_id_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['unit'], name='products_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['mrp'], name='products_mrp_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gst_rate'], name='products_gst_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_veg'], name='products_is_veg_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_organic'], name='products_is_organic_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_fresh'], name='products_is_fresh_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_deleted'], name='products_is_deleted_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('mrp__gte', models.F('price'))), name='products_mrp_gte_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('reviews_count__gte', 0)), name='products_reviews_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='products_stock_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='products_discount_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='products_price_gte_0'),
        ),
        migrations.AddIndex(
            model_name='comboproduct',
            index=models.Index(fields=['combo'], name='combos_products_combo_idx'),
        ),
        migrations.AddIndex(
            model_name='comboproduct',
            index=models.Index(fields=['product'], name='combos_products_product_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comboproduct',
            unique_together={('combo', 'product')},
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['is_active'], name='combos_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['is_deleted'], name='combos_is_deleted_idx'),
        ),
        migrations.AddConstraint(
            model_name='combo',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 50)), name='combos_discount_percent_range'),
        ),
    ]
