# Generated by Django 6.0.2 on 2026-02-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_cat_active_idx',
            old_name='products_category_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_name_idx',
            old_name='products_name_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_is_deleted_idx',
            old_name='products_is_deleted_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
