# Generated by Django 6.0.2 on 2026-02-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='var(--primary-pink)', help_text='CSS color variable or hex color for category', max_length=50),
        ),
    ]
