# Generated by Django 6.0.2 on 2026-02-24 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.productreview'),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user'], name='product_reviews_user_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product'], name='product_reviews_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['order'], name='product_reviews_order_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'is_approved', 'is_deleted'], name='product_reviews_product_approved_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user', 'is_deleted'], name='product_reviews_user_is_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='product_reviews_rating_idx'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.CheckConstraint(condition=models.Q(('comment__regex', '^[\\s\\S]{0,1000}$')), name='product_reviews_comment_length'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='product_reviews_rating_range'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('user', 'product', 'order')},
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['review'], name='review_helpful_votes_review_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['user'], name='review_helpful_votes_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'user')},
        ),
    ]
