# Generated by Django 6.0.2 on 2026-02-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productreview',
            new_name='prod_rev_prod_app_idx',
            old_name='product_reviews_product_approved_idx',
        ),
        migrations.RenameIndex(
            model_name='productreview',
            new_name='prod_rev_user_del_idx',
            old_name='product_reviews_user_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewhelpful',
            new_name='rev_help_votes_rev_idx',
            old_name='review_helpful_votes_review_idx',
        ),
    ]
