# Generated by Django 6.0.2 on 2026-02-24 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='wishlist_items_user_idx'), models.Index(fields=['product'], name='wishlist_items_product_idx'), models.Index(fields=['user', 'is_deleted'], name='wishlist_items_user_is_deleted_idx'), models.Index(fields=['product', 'is_deleted'], name='wishlist_items_product_is_deleted_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
