# Generated by Django 6.0.2 on 2026-02-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='wish_items_user_del_idx',
            old_name='wishlist_items_user_is_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='wish_items_prod_del_idx',
            old_name='wishlist_items_product_is_deleted_idx',
        ),
    ]
