# Generated by Django 6.0.2 on 2026-02-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('search', 'Search'), ('filter_apply', 'Filter Apply'), ('add_to_wishlist', 'Add to Wishlist'), ('remove_from_wishlist', 'Remove from Wishlist'), ('coupon_apply', 'Coupon Apply'), ('checkout', 'Checkout'), ('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('contact_form', 'Contact Form Submit'), ('profile_update', 'Profile Update'), ('settings_change', 'Settings Change')], max_length=50)),
                ('page', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
