# Generated by Django 6.0.2 on 2026-02-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('search', 'Search'), ('filter_apply', 'Filter Apply'), ('add_to_wishlist', 'Add to Wishlist'), ('remove_from_wishlist', 'Remove from Wishlist'), ('coupon_apply', 'Coupon Apply'), ('checkout', 'Checkout'), ('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('contact_form', 'Contact Form Submit'), ('profile_update', 'Profile Update'), ('settings_change', 'Settings Change')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
