# Generated by Django 6.0.2 on 2026-02-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='act_logs_user_created_idx',
            old_name='activity_logs_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='act_logs_action_created_idx',
            old_name='activity_logs_action_created_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('search', 'Search'), ('filter_apply', 'Filter Apply'), ('add_to_wishlist', 'Add to Wishlist'), ('remove_from_wishlist', 'Remove from Wishlist'), ('coupon_apply', 'Coupon Apply'), ('checkout', 'Checkout'), ('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('contact_form', 'Contact Form Submit'), ('profile_update', 'Profile Update'), ('settings_change', 'Settings Change')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='page',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
