# Generated by Django 6.0.2 on 2026-02-24 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='activity_logs_user_created_idx'),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX activity_logs_action_created_idx ON activity_logs(action, created_at);",
            reverse_sql="DROP INDEX IF EXISTS activity_logs_action_created_idx;",
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['page'], name='activity_logs_page_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['session_id'], name='activity_logs_session_id_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='activity_logs_user_idx'),
        ),
    ]
