# Generated by Django 6.0.2 on 2026-02-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_alter_activitylog_action_alter_activitylog_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='act_log_act_created_idx',
            old_name='activity_log_action_created_idx',
        ),
    ]
