# Generated by Django 6.0.2 on 2026-02-24 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(default='')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('category', 'Category')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applicable_categories', models.JSONField(default=list)),
                ('first_order_only', models.BooleanField(default=False)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupons',
                'indexes': [models.Index(fields=['code'], name='coupons_code_idx'), models.Index(fields=['is_active'], name='coupons_is_active_idx'), models.Index(fields=['is_active', 'valid_until'], name='coupons_active_valid_idx'), models.Index(fields=['applicable_categories'], name='coupons_categories_gin'), models.Index(fields=['code', 'is_active'], name='coupons_code_is_active_idx'), models.Index(fields=['is_deleted'], name='coupons_is_deleted_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
            ],
            options={
                'db_table': 'coupon_usages',
            },
        ),
    ]
