# Generated by Django 6.0.2 on 2026-02-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='couponusage',
            new_name='coupon_usages_user_del_idx',
            old_name='coupon_usages_user_is_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='couponusage',
            new_name='coupon_usages_coup_del_idx',
            old_name='coupon_usages_coupon_is_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='couponusage',
            new_name='coupon_usages_is_del_idx',
            old_name='coupon_usages_is_deleted_idx',
        ),
    ]
