# Generated by Django 6.0.2 on 2026-02-24 09:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), help_text='Tax rate as decimal (e.g., 0.08 for 8%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('standard_delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Standard delivery charge', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('express_delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Express delivery charge', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Order amount above which delivery is free', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('site_name', models.CharField(default='HappyGroceries', max_length=100)),
                ('site_currency', models.CharField(default='₹', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='site_settings_tax_rate_gte_0'), models.CheckConstraint(condition=models.Q(('standard_delivery_charge__gte', 0)), name='site_settings_standard_delivery_gte_0'), models.CheckConstraint(condition=models.Q(('express_delivery_charge__gte', 0)), name='site_settings_express_delivery_gte_0'), models.CheckConstraint(condition=models.Q(('free_delivery_threshold__gte', 0)), name='site_settings_free_threshold_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='SortOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sort Option',
                'verbose_name_plural': 'Sort Options',
                'db_table': 'sort_options',
                'ordering': ['order', 'label'],
                'indexes': [models.Index(fields=['order'], name='sort_options_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='sort_options_order_gte_0')],
            },
        ),
    ]
