# Generated by Django 6.0.2 on 2026-02-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.08, max_digits=5)),
                ('standard_delivery_charge', models.DecimalField(decimal_places=2, default=40.0, max_digits=10)),
                ('express_delivery_charge', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('site_name', models.CharField(default='HappyGroceries', max_length=100)),
                ('site_currency', models.CharField(default='₹', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='SortOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sort_options',
                'indexes': [models.Index(fields=['order'], name='sort_options_order_idx')],
            },
        ),
    ]
