# Generated by Django 6.0.2 on 2026-02-24 07:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), help_text='Tax rate as decimal (e.g., 0.08 for 8%)', max_digits=5)),
                ('standard_delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Standard delivery charge', max_digits=10)),
                ('express_delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Express delivery charge', max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Order amount above which delivery is free', max_digits=10)),
                ('site_name', models.CharField(default='HappyGroceries', max_length=100)),
                ('site_currency', models.CharField(default='₹', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='SortOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sort Option',
                'verbose_name_plural': 'Sort Options',
                'db_table': 'sort_options',
                'ordering': ['order', 'label'],
                'indexes': [models.Index(fields=['order'], name='sort_option_order_4ec7d0_idx')],
            },
        ),
    ]
